# Generated by Django 5.1.2 on 2025-01-07 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_bring",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_provided",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_type",
            field=models.CharField(
                blank=True,
                choices=[("day_trip", "Day Trip"), ("overnight_trip", "Overnight")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_leader",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
