# Generated by Django 5.1.2 on 2025-01-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_alter_student_user_alter_trip_trip_bring_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_trip_leader",
            field=models.BooleanField(default=False),
        ),
    ]
