# Generated by Django 5.1.2 on 2025-01-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_student_is_trip_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlist',
            old_name='student',
            new_name='waitlist_student',
        ),
        migrations.RenameField(
            model_name='waitlist',
            old_name='trip',
            new_name='waitlist_trip',
        ),
        migrations.CreateModel(
            name='Enemies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainers', to='webapp.student')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='webapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='TripLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
                ('leader_subclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subclub')),
            ],
        ),
    ]
