# Generated by Django 5.1.2 on 2025-01-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_student_waitlist_waitlist_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='favorite_subclubs',
            field=models.ManyToManyField(blank=True, to='webapp.subclub'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='student',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
