# Generated by Django 5.1.2 on 2025-01-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_student_is_trip_leader'),
        ('webapp', '0005_rename_student_waitlist_waitlist_student_and_more'),
    ]

    operations = [
    ]
