# Generated by Django 5.1.2 on 2025-01-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_trip_trip_bring_trip_trip_level_trip_trip_location_and_more'),
        ('webapp', '0006_merge_20250121_1306'),
        ('webapp', '0006_student_allergies_student_class_year_and_more'),
    ]

    operations = [
    ]
